---
- hosts: tower
  collections:
  - ansible.tower # when using ansible.tower

  - name: Playbook to configure subscription
    tower_license:
    # manifest: "/vagrant/tower/manifest_Tower-POC.zip"
    