---
- name: Playbook for Using a Variety of Tower Modules
  hosts: tower
  collections:
    - ansible.tower # when using ansible.tower

    - name: Upload manifest
      tower_license:
        manifest: "/vagrant/tower/manifest_Tower-POC.zip"
        eula_accepted: yes





    