collections:
- ansible.tower # when using ansible.tower

- name: Playbook to configure subscription
  hosts: localhost

  tower_license:
  manifest: "/vagrant/tower/manifest_Tower-POC.zip"
  # eula_accepted: True