---
- hosts: localhost
  collections:
  - ansible.tower # when using ansible.tower
tasks:
  - name: Playbook to configure subscription
    tower_license:
    manifest: "/vagrant/tower/manifest_Tower-POC.zip"
    eula_accepted: True